export interface Food {
  id: number;
  title: string;
  protein: number;
  fat: number;
  carbs: number;
  calories: number;
  per: number;
}

export const foods: Food[] = [
  {
    id: 1,
    title: "Творог 5%",
    protein: 16,
    fat: 5,
    carbs: 3,
    calories: 121,
    per: 100,
  },
  {
    id: 2,
    title: "Греческий йогурт 2%",
    protein: 10,
    fat: 2,
    carbs: 4,
    calories: 73,
    per: 100,
  },
  {
    id: 3,
    title: "Куриная грудка",
    protein: 23,
    fat: 1.5,
    carbs: 0,
    calories: 110,
    per: 100,
  },
  {
    id: 4,
    title: "Филе бедра куриного",
    protein: 18,
    fat: 8,
    carbs: 0,
    calories: 150,
    per: 100,
  },
  {
    id: 5,
    title: "Хлеб цельнозерновой",
    protein: 8,
    fat: 2,
    carbs: 45,
    calories: 230,
    per: 100,
  },
  {
    id: 6,
    title: "Овсянка (сухая)",
    protein: 12,
    fat: 6,
    carbs: 65,
    calories: 370,
    per: 100,
  },
  {
    id: 7,
    title: "Рис варёный",
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    calories: 130,
    per: 100,
  },
  {
    id: 8,
    title: "Гречка варёная",
    protein: 3.4,
    fat: 0.6,
    carbs: 19,
    calories: 92,
    per: 100,
  },
  {
    id: 9,
    title: "Яйцо куриное",
    protein: 13,
    fat: 11,
    carbs: 1,
    calories: 155,
    per: 100,
  },
  {
    id: 10,
    title: "Тунец в собственном соку",
    protein: 25,
    fat: 1,
    carbs: 0,
    calories: 100,
    per: 100,
  },
  {
    id: 11,
    title: "Банан",
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    calories: 90,
    per: 100,
  },
  {
    id: 12,
    title: "Говядина нежирная",
    protein: 22,
    fat: 5,
    carbs: 0,
    calories: 133,
    per: 100,
  },
  {
    id: 13,
    title: "Лосось",
    protein: 20,
    fat: 13,
    carbs: 0,
    calories: 200,
    per: 100,
  },
  {
    id: 14,
    title: "Треска",
    protein: 18,
    fat: 0.7,
    carbs: 0,
    calories: 82,
    per: 100,
  },
  {
    id: 15,
    title: "Сывороточный протеин",
    protein: 75,
    fat: 3,
    carbs: 7,
    calories: 370,
    per: 100,
  },
];
